version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Running build (if any)..."
      - npm run build || echo "No build script defined"

  post_build:
    commands:
      - echo "Build completed. Preparing for deployment..."

artifacts:
  files:
    - '**/*'
